
name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
  Practice:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Show what's in the directory
      run: |
        ls
    - name: Show what all is in the parent directory
      run: |
        cd ..
        ls
        
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        cd ../Orbital
        nuget restore Imi.Project.sln
        msbuild Imi.Project.Mobile/Imi.Project.Mobile.Android/Imi.Project.Mobile.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  UWP:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: UWP
      run: |
        cd ../Orbital
        nuget restore Imi.Project.sln
        msbuild Imi.Project.Mobile/Imi.Project.Mobile.UWP/Imi.Project.Mobile.UWP.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
